name: Deploy Backend of Resume Project to Azure

on:
  push:
    branches: []

jobs:
  job: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Terraform Installation
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.9.5'
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CRED }}
      
      - name: Terraform Init
        run: terraform init -backend-config="backend.tfstate"
      
      - name: Terraform fmt
        run: terraform fmt -check
      
      - name: Terraform validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -parallelism=1 tfplan